#!/usr/bin/env bash

while [ "$1" ]; do
    case "$1" in
    up)
        docker-compose -f "docker-compose.yaml" up -d --build && exit 0
      ;;
    down)
        docker-compose -f "docker-compose.yaml" down && exit 0
    esac
done